#! /bin/bash

rainbow=("violet" "indigo" "blue" "green" "yellow" "orange" "red")
echo "Colors of the rainbow:"
echo ${rainbow[*]}

echo "Before swapping positions 0 and 4, the colors are arranged as:"
echo ${rainbow[*]}
temp=${rainbow[4]}
rainbow[4]=${rainbow[0]}
rainbow[0]=$temp
echo "After swapping positions 0 and 4, the colors are rearranged as:"
echo ${rainbow[*]}
